const products = [
    {
        id: 1,
        category: 'Analgésicos',
        name: 'Actron 600',
        description: '10 cápsulas, analgésico y antiinflamatorio',
        price: 196,
        image: '/images/actron600.jpg',
        stock: 10,
    },
    {
        id: 2,
        category: 'Analgésicos',
        name: 'Perifar 600',
        description: '10 cápsulas, analgésico y antiinflamatorio',
        price: 186,
        image: '/images/perifar600.jpg',
        stock: 8,
    },
    {
        id: 3,
        category: 'Analgésicos',
        name: 'Dolosedol 500',
        description: '50 comprimidos, paracetamol, analgésico y antifebril',
        price: 199,
        image: '/images/dolosedol500.jpg',
        stock: 15,
    },
    {
        id: 4,
        category: 'Analgésicos',
        name: 'Dolex 500',
        description: '50 comprimidos, paracetamol, analgésico y antifebril',
        price: 244,
        image: '/images/dolex500.jpg',
        stock: 20,
    },
    {
        id: 5,
        category: 'Suplementos',
        name: 'Colagenol C',
        description: '30 cápsulas, mejora de articulaciones',
        price: 1300,
        image: '/images/colagenolC.jpg',
        stock: 10,
    },
    {
        id: 6,
        category: 'Suplementos',
        name: 'Mega Omega 3',
        description: '30 cápsulas, prevención cardiovascular y articular',
        price: 699,
        image: '/images/omega3.jpg',
        stock: 12,
    },
    {
        id: 7,
        category: 'Suplementos',
        name: 'Citrato de Magnesio',
        description: '100 comprimidos, mejora digestión, salud ósea y muscular',
        price: 968,
        image: '/images/magnesio.jpg',
        stock: 18,
    },
    {
        id: 8,
        category: 'Suplementos',
        name: 'Harina de Orujo',
        description: '100g, ayuda contra el envejecimiento celular y varias enfermedades',
        price: 390,
        image: '/images/orujo.jpg',
        stock: 25,
    },
    {
        id: 9,
        category: 'Productos de Higiene',
        name: '',
        description: '',
        price: 0,
        image: '/images/productoHigiene1.jpg',
        stock: 0,
    },
    // Añadir más productos para las categorías vacías como Productos de Higiene y Anticonceptivos
];

export default products;
